name: Build Docker image
on:
  push:
    branches:
      - master
      - Backend
jobs:
  push_to_ghcr:
    name: Push to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        env: 
          tags: ${{ format('{0},{1}', format('ghcr.io/{0}:latest', github.repository), format('ghcr.io/{0}:{1}', github.repository, github.ref_name)) }}
        uses: docker/build-push-action@v2
        with:
          context: ./server
          tags: ${{ env.tags }}
          push: true
